server:
  port: 8088

spring:
  cloud:
    config:
      server:
        composite:
            - type: native
              search-locations: classpath:/shared
  profiles:
    active: composite
  security:
    user:
      password: nizomiddin